
from typing import List, Tuple, Protocol

class IOCR(Protocol):
    def parse_entries(self, image_path: str) -> List[Tuple[str, int]]: ...

class IRepository(Protocol):
    def init(self) -> None: ...
    def add_page(self, path: str, ts: str) -> int: ...
    def add_entry(self, name: str, amount_st: int, ts: str, page_id: int | None) -> None: ...
    def search_by_name(self, q: str) -> List[Tuple[str,int]]: ...
